### ISSUE TITLE
Missing pooch as dependency?

### ISSUE THREAD

**Issue by willemarcel** [kraina-ai/overturemaestro#12]
I've installed it and had this error when importing `overturemaestro`

```
>>> import overturemaestro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wille/.virtualenvs/overture/lib/python3.10/site-packages/overturemaestro/__init__.py", line 14, in <module>
    from overturemaestro.release_index import get_available_theme_type_pairs
  File "/Users/wille/.virtualenvs/overture/lib/python3.10/site-packages/overturemaestro/release_index.py", line 20, in <module>
    from pooch import file_hash, retrieve
ModuleNotFoundError: No module named 'pooch'
```

**Comment by RaczeQ** [comment]
Thank you for this catch @willemarcel! That's what I get for rushing a release without tests and CI/CD 😅 
Fixed in 0.0.2 😉
